version: 2

builds:
  - id: ragnarok-services
    binary: ragnarok-services
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"