package types

// Protocol represents an IP protocol number (0-255, or -1 for all).
type Protocol int16

const (
	ProtocolAll Protocol = -1 // Matches all protocols

	ProtocolHOPOPT          Protocol = 0   // IPv6 Hop‑by‑Hop Option
	ProtocolICMP            Protocol = 1   // Internet Control Message Protocol
	ProtocolIGMP            Protocol = 2   // Internet Group Management Protocol
	ProtocolGGP             Protocol = 3   // Gateway‑to‑Gateway Protocol
	ProtocolIPIP            Protocol = 4   // IP in IP (encapsulation)
	ProtocolST              Protocol = 5   // Internet Stream Protocol
	ProtocolTCP             Protocol = 6   // Transmission Control Protocol
	ProtocolCBT             Protocol = 7   // Core‑Based Trees
	ProtocolEGP             Protocol = 8   // Exterior Gateway Protocol
	ProtocolIGP             Protocol = 9   // any private Interior Gateway
	ProtocolBBN_RCC_MON     Protocol = 10  // BBN RCC Monitoring
	ProtocolNVP_II          Protocol = 11  // Network Voice Protocol
	ProtocolPUP             Protocol = 12  // Xerox PUP
	ProtocolARGUS           Protocol = 13  // ARGUS
	ProtocolEMCON           Protocol = 14  // EMCON
	ProtocolXNET            Protocol = 15  // Cross‑Net Debugger
	ProtocolCHAOS           Protocol = 16  // CHAOS
	ProtocolUDP             Protocol = 17  // User Datagram Protocol
	ProtocolMUX             Protocol = 18  // Multiplexing
	ProtocolDCN_MEAS        Protocol = 19  // DCN Measurement Subsystems
	ProtocolHMP             Protocol = 20  // Host Monitoring Protocol
	ProtocolPRM             Protocol = 21  // Packet Radio Measurement
	ProtocolXNS_IDP         Protocol = 22  // Xerox NS IDP
	ProtocolTRUNK1          Protocol = 23  // Trunk‑1
	ProtocolTRUNK2          Protocol = 24  // Trunk‑2
	ProtocolLEAF1           Protocol = 25  // Leaf‑1
	ProtocolLEAF2           Protocol = 26  // Leaf‑2
	ProtocolRDP             Protocol = 27  // Reliable Data Protocol
	ProtocolIRTP            Protocol = 28  // Internet Reliable Transaction Protocol
	ProtocolISO_TP4         Protocol = 29  // ISO TP4
	ProtocolNETBLT          Protocol = 30  // Bulk Data Transfer Protocol
	ProtocolMFE_NSP         Protocol = 31  // MFE Network Services Protocol
	ProtocolMERIT_INP       Protocol = 32  // MERIT Internodal Protocol
	ProtocolDCCP            Protocol = 33  // Datagram Congestion Control Protocol
	Protocol3PC             Protocol = 34  // Third Party Connect Protocol
	ProtocolIDPR            Protocol = 35  // Inter‑Domain Policy Routing
	ProtocolXTP             Protocol = 36  // Xpress Transport Protocol
	ProtocolDDP             Protocol = 37  // Datagram Delivery Protocol
	ProtocolIDPR_CMTP       Protocol = 38  // IDPR Control Message Transport
	ProtocolTP_PLUSPLUS     Protocol = 39  // TP++ Transport Protocol
	ProtocolIL              Protocol = 40  // IL Transport Protocol
	ProtocolIPv6            Protocol = 41  // IPv6 encapsulation
	ProtocolSDRP            Protocol = 42  // Source Demand Routing Protocol
	ProtocolIPv6_ROUTE      Protocol = 43  // IPv6 Routing Header
	ProtocolIPv6_FRAG       Protocol = 44  // IPv6 Fragment Header
	ProtocolIDRP            Protocol = 45  // Inter‑Domain Routing Protocol
	ProtocolRSVP            Protocol = 46  // Resource Reservation Protocol
	ProtocolGRE             Protocol = 47  // Generic Routing Encapsulation
	ProtocolDSR             Protocol = 48  // Dynamic Source Routing Protocol
	ProtocolBNA             Protocol = 49  // Burroughs Network Architecture
	ProtocolESP             Protocol = 50  // Encapsulating Security Payload
	ProtocolAH              Protocol = 51  // Authentication Header
	ProtocolI_NLSP          Protocol = 52  // Integrated Net Layer Security
	ProtocolSwIPe           Protocol = 53  // SwIPe
	ProtocolNARP            Protocol = 54  // NBMA Address Resolution Protocol
	ProtocolMOBILE          Protocol = 55  // IP Mobility (Minimal Encap)
	ProtocolTLSP            Protocol = 56  // Transport Layer Security Protocol
	ProtocolSKIP            Protocol = 57  // Simple Key‑Management for IP
	ProtocolIPv6_ICMP       Protocol = 58  // ICMP for IPv6
	ProtocolIPv6_NoNxt      Protocol = 59  // No Next Header for IPv6
	ProtocolIPv6_Opts       Protocol = 60  // Destination Options for IPv6
	ProtocolInternProto     Protocol = 61  // any host‑internal protocol
	ProtocolCFTP            Protocol = 62  // CFTP
	ProtocolLocalNet        Protocol = 63  // any local network
	ProtocolSAT_EXPAK       Protocol = 64  // SATNET/Backroom EXPAK
	ProtocolKRYPTOLAN       Protocol = 65  // Kryptolan
	ProtocolRVD             Protocol = 66  // Remote Virtual Disk
	ProtocolIPPC            Protocol = 67  // Internet Pluribus Packet Core
	ProtocolDFS             Protocol = 68  // any distributed file system
	ProtocolSAT_MON         Protocol = 69  // SATNET Monitoring
	ProtocolVISA            Protocol = 70  // VISA Protocol
	ProtocolIPCU            Protocol = 71  // Internet Packet Core Utility
	ProtocolCPNX            Protocol = 72  // Computer Protocol Network Executive
	ProtocolCPHB            Protocol = 73  // Computer Protocol Heartbeat
	ProtocolWSN             Protocol = 74  // Wang Span Network
	ProtocolPVP             Protocol = 75  // Packet Video Protocol
	ProtocolBR_SAT_MON      Protocol = 76  // Backroom SATNET Monitoring
	ProtocolSUN_ND          Protocol = 77  // SUN ND Protocol
	ProtocolWB_MON          Protocol = 78  // Wideband Monitoring
	ProtocolWB_EXPAK        Protocol = 79  // Wideband EXPAK
	ProtocolISO_IP          Protocol = 80  // ISO Internet Protocol
	ProtocolVMTP            Protocol = 81  // Versatile Message Transaction Protocol
	ProtocolSECURE_VMTP     Protocol = 82  // Secure VMTP
	ProtocolVINES           Protocol = 83  // VINES
	ProtocolTTP             Protocol = 84  // Transaction Transport Protocol
	ProtocolNSFNET_IGP      Protocol = 85  // NSFNET‑IGP
	ProtocolDGP             Protocol = 86  // Dissimilar Gateway Protocol
	ProtocolTCF             Protocol = 87  // TCF
	ProtocolEIGRP           Protocol = 88  // EIGRP
	ProtocolOSPF            Protocol = 89  // OSPF
	ProtocolSprite_RPC      Protocol = 90  // Sprite RPC Protocol
	ProtocolLARP            Protocol = 91  // Locus Address Resolution Protocol
	ProtocolMTP             Protocol = 92  // Multicast Transport Protocol
	ProtocolAX25            Protocol = 93  // AX.25
	ProtocolOS_PROTO        Protocol = 94  // KA9Q NOS IP-in-IP encapsulation
	ProtocolMICP            Protocol = 95  // Mobile Internetworking Control Protocol
	ProtocolSCC_SPG         Protocol = 96  // Semaphore Comms Security Protocol
	ProtocolETHERIP         Protocol = 97  // Ethernet-within-IP Encapsulation
	ProtocolENCAP           Protocol = 98  // Encapsulation Header
	ProtocolPrivateEnc      Protocol = 99  // any private encryption scheme
	ProtocolGMTP            Protocol = 100 // GMTP
	ProtocolIFMP            Protocol = 101 // Ipsilon Flow Mgmt Protocol
	ProtocolPNNI            Protocol = 102 // PNNI
	ProtocolPIM             Protocol = 103 // Protocol Independent Multicast
	ProtocolARIS            Protocol = 104 // ARIS
	ProtocolSCPS            Protocol = 105 // SCPS
	ProtocolQNX             Protocol = 106 // QNX
	ProtocolANET            Protocol = 107 // Active Networks
	ProtocolIPComp          Protocol = 108 // IP Payload Compression Protocol
	ProtocolSNP             Protocol = 109 // Sitara Networks Protocol
	ProtocolCompaqPeer      Protocol = 110 // Compaq Peer Protocol
	ProtocolIPX_IN_IP       Protocol = 111 // IPX in IP
	ProtocolVRRP            Protocol = 112 // Virtual Router Redundancy Protocol
	ProtocolPGM             Protocol = 113 // PGM Reliable Transport
	ProtocolZeroHop         Protocol = 114 // Any 0‑hop protocol
	ProtocolL2TPv3          Protocol = 115 // L2TPv3
	ProtocolDDX             Protocol = 116 // D‑II Data Exchange
	ProtocolIATP            Protocol = 117 // Interactive Agent Transfer Protocol
	ProtocolSTP_PROTO       Protocol = 118 // Schedule Transfer Protocol
	ProtocolSRP             Protocol = 119 // SpectraLink Radio Protocol
	ProtocolUTI             Protocol = 120 // Universal Transport Interface
	ProtocolSMP_PROTO       Protocol = 121 // Simple Message Protocol
	ProtocolSM_PROTO        Protocol = 122 // Simple Multicast Protocol
	ProtocolPTP_PROTO       Protocol = 123 // Performance Transparency Protocol
	ProtocolISIS4           Protocol = 124 // IS‑IS over IPv4
	ProtocolFIRE            Protocol = 125 // Flexible Intra‑AS Routing Env
	ProtocolCRTP            Protocol = 126 // Combat Radio Transport Protocol
	ProtocolCRUDP           Protocol = 127 // Combat Radio UDP
	ProtocolSSCOPMCE        Protocol = 128 // SSCOPMCE
	ProtocolIPLT_PROTO      Protocol = 129 // IPLT
	ProtocolSPS             Protocol = 130 // Secure Packet Shield
	ProtocolPIPE            Protocol = 131 // Private IP Encapsulation
	ProtocolSCTP            Protocol = 132 // Stream Control Transmission Protocol
	ProtocolFC_PROTO        Protocol = 133 // Fibre Channel
	ProtocolRSVP_E2E_IGNORE Protocol = 134 // RSVP End‑to‑End Ignore
	ProtocolMOBILITY_HDR    Protocol = 135 // IPv6 Mobility Header
	ProtocolUDPLite         Protocol = 136 // Lightweight UDP
	ProtocolMPLS_IN_IP      Protocol = 137 // MPLS‑in‑IP
	ProtocolMANET           Protocol = 138 // MANET
	ProtocolHIP             Protocol = 139 // Host Identity Protocol
	ProtocolShim6           Protocol = 140 // SHIM6
	ProtocolWESP            Protocol = 141 // Wrapped ESP
	ProtocolROHC            Protocol = 142 // Robust Header Compression
	ProtocolEthernet        Protocol = 143 // Segment Routing over IPv6
	ProtocolAGGFRAG         Protocol = 144 // AGGFRAG for ESP
	ProtocolNSH             Protocol = 145 // Network Service Header
	ProtocolHoma            Protocol = 146 // Homa transport protocol
	ProtocolBIT_EMU         Protocol = 147 // Bit‑stream Emulation

	// 148-252 unassigned
	ProtocolExperiment1 Protocol = 253 // for experimentation
	ProtocolExperiment2 Protocol = 254 // for experimentation
	ProtocolReserved    Protocol = 255 // reserved
)
